<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Paws.Abstractions\Paws.Abstractions.csproj" />
    <ProjectReference Include="..\Paws.Drivers\Paws.Drivers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Realm" Version="20.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
