### Get All Themes
GET http://localhost:5088/api/themes
Accept: application/json

### Import a new theme
POST http://localhost:5088/api/themes/import
Content-Type: application/json

{
  "filePath": "C:\\theme\\my-test-theme.pawstheme"
}

###
